# Login non existent user
POST http://localhost:8000/login/
Content-Type: application/json

{
  "email": "doesnt_exists@gmail.com",
  "password": "12345"
}

###

# Login existing user but with wrong password
POST http://localhost:8000/login/
Content-Type: application/json

{
  "email": "julio3@gmail.com",
  "password": "wrongpassword"
}

###

# Successful login to admin account
POST http://localhost:8000/login/
Content-Type: application/json

{
  "email": "julio@gmail.com",
  "password": "234"
}

###

# Successful login to user account
POST http://localhost:8000/login/
Content-Type: application/json

{
  "email": "julio3@gmail.com",
  "password": "2343"
}

###

# Register user with invalid email
POST http://localhost:8000/signup/
Content-Type: application/json

{
  "name": "julio",
  "email": "julio@gmail.com",
  "password": "555"
}

###

# Register user successfully
POST http://localhost:8000/signup/
Content-Type: application/json

{
  "name": "julio",
  "email": "julio5@gmail.com",
  "password": "234"
}

###

# Retrieve users
GET http://localhost:8000/users/
#Authorization: Bearer header.payload.signature

###

# Get a single user
GET http://localhost:8000/users/5e1e97d15758b61ce475d603

###

# Create user
POST http://localhost:8000/users/
Content-Type: application/json

{
  "name": "Julio4",
  "email": "julio4@gmail.com",
  "password": "2343",
  "role": "user"
}

###

# Update user
PATCH http://localhost:8000/users/5e24bc34b1cf7521c4e3afc6
Content-Type: application/json

{
  "name": "Jose"
}

###

# Delete user
DELETE http://localhost:8000/users/5e24bc34b1cf7521c4e3afc6

